<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260215233831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE artist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, spotify_id VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1599687A905FC5C ON artist (spotify_id)');
        $this->addSql('CREATE TABLE chart (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, image_url VARCHAR(255) DEFAULT NULL, scraping_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, provider_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5562A2AA53A8AA ON chart (provider_id)');
        $this->addSql('CREATE UNIQUE INDEX chart_provider_slug_unique ON chart (provider_id, slug)');
        $this->addSql('CREATE TABLE chart_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, snapshot_date DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chart_id INT NOT NULL, song_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD10222CBEF83E0A ON chart_entry (chart_id)');
        $this->addSql('CREATE INDEX IDX_CD10222CA0BDB2F3 ON chart_entry (song_id)');
        $this->addSql('CREATE UNIQUE INDEX chart_song_snapshot_unique ON chart_entry (chart_id, song_id, snapshot_date)');
        $this->addSql('CREATE TABLE chart_provider (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, base_url VARCHAR(255) DEFAULT NULL, scraping_config JSON DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C5E116E35E237E06 ON chart_provider (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C5E116E3989D9B62 ON chart_provider (slug)');
        $this->addSql('CREATE TABLE song (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, spotify_id VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33EDEEA1A905FC5C ON song (spotify_id)');
        $this->addSql('CREATE TABLE song_artist (song_id INT NOT NULL, artist_id INT NOT NULL, PRIMARY KEY (song_id, artist_id))');
        $this->addSql('CREATE INDEX IDX_722870DA0BDB2F3 ON song_artist (song_id)');
        $this->addSql('CREATE INDEX IDX_722870DB7970CF8 ON song_artist (artist_id)');
        $this->addSql('CREATE TABLE spotify_playlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spotify_id VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, snapshot_id VARCHAR(255) DEFAULT NULL, user_id VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chart_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4C05F8CA905FC5C ON spotify_playlist (spotify_id)');
        $this->addSql('CREATE INDEX IDX_A4C05F8CBEF83E0A ON spotify_playlist (chart_id)');
        $this->addSql('ALTER TABLE chart ADD CONSTRAINT FK_E5562A2AA53A8AA FOREIGN KEY (provider_id) REFERENCES chart_provider (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chart_entry ADD CONSTRAINT FK_CD10222CBEF83E0A FOREIGN KEY (chart_id) REFERENCES chart (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chart_entry ADD CONSTRAINT FK_CD10222CA0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE song_artist ADD CONSTRAINT FK_722870DA0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE song_artist ADD CONSTRAINT FK_722870DB7970CF8 FOREIGN KEY (artist_id) REFERENCES artist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE spotify_playlist ADD CONSTRAINT FK_A4C05F8CBEF83E0A FOREIGN KEY (chart_id) REFERENCES chart (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chart DROP CONSTRAINT FK_E5562A2AA53A8AA');
        $this->addSql('ALTER TABLE chart_entry DROP CONSTRAINT FK_CD10222CBEF83E0A');
        $this->addSql('ALTER TABLE chart_entry DROP CONSTRAINT FK_CD10222CA0BDB2F3');
        $this->addSql('ALTER TABLE song_artist DROP CONSTRAINT FK_722870DA0BDB2F3');
        $this->addSql('ALTER TABLE song_artist DROP CONSTRAINT FK_722870DB7970CF8');
        $this->addSql('ALTER TABLE spotify_playlist DROP CONSTRAINT FK_A4C05F8CBEF83E0A');
        $this->addSql('DROP TABLE artist');
        $this->addSql('DROP TABLE chart');
        $this->addSql('DROP TABLE chart_entry');
        $this->addSql('DROP TABLE chart_provider');
        $this->addSql('DROP TABLE song');
        $this->addSql('DROP TABLE song_artist');
        $this->addSql('DROP TABLE spotify_playlist');
    }
}
